GET  http://localhost:7777/users


###
POST http://localhost:7777/users
Content-Type: application/json

{
    "firstname": "Duy",
    "lastname": "Huynh",
    "username":"123",
    "email":"D123",
    "dnumber":"D123",
    "password":"123",
    "phone":"123"
}

###
POST http://localhost:7777/login
Content-Type: application/json

{
    "email":"D123",
    "password":"123"
}